name: Angular CI

on:
  # Trigger the workflow on push or pull request
  # for master, dev, and release branches
  push:
    branches:
      - master
      - 'development'
      - 'release'
  pull_request:
    branches:
      - master
      - 'development'
      - 'release'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build:prod
